# OIC DevOps Configuration File Template
# Create a file named .oic_config.yaml in your home directory or specify a custom path

# Default profile - used when no profile is specified
default:
  instance_url: "https://your-instance-name.integration.ocp.oraclecloud.com"
  identity_domain: "your-identity-domain"
  username: "your-username"
  password: "your-password"
  scope: "your-scope"  # Optional
  timeout: 300  # Connection timeout in seconds (optional)
  verify_ssl: true  # Verify SSL certificates (optional)

# Development environment
dev:
  instance_url: "https://your-dev-instance.integration.ocp.oraclecloud.com"
  identity_domain: "your-dev-identity-domain"
  username: "your-dev-username"
  password: "your-dev-password"
  scope: "your-dev-scope"  # Optional
  timeout: 300
  verify_ssl: true

# Test environment
test:
  instance_url: "https://your-test-instance.integration.ocp.oraclecloud.com"
  identity_domain: "your-test-identity-domain"
  username: "your-test-username"
  password: "your-test-password"
  scope: "your-test-scope"  # Optional
  timeout: 300
  verify_ssl: true

# Production environment
prod:
  instance_url: "https://your-prod-instance.integration.ocp.oraclecloud.com"
  identity_domain: "your-prod-identity-domain"
  username: "your-prod-username"
  password: "your-prod-password"
  scope: "your-prod-scope"  # Optional
  timeout: 600  # Longer timeout for production
  verify_ssl: true
