[tool.ruff]
target-version = "py39"  # Target Python 3.9+

[tool.ruff.lint]
select = ["ALL"]  # Enable all rules
ignore = ["PERF203", "G004", "COM812", "W191", "D206", "Q000", "Q003", "D203", "D211", "D212", "D213"]  # Ignore specific rules, including conflicting docstring rules

[tool.ruff.lint.isort]
split-on-trailing-comma = false  # Align with formatter

[tool.ruff.format]
quote-style = "single"  # Use single quotes
indent-style = "tab"
skip-magic-trailing-comma = true
# Specify files/directories to exclude from formatting, if needed
exclude = ["venv/", "build/"]  # Example; adjust or remove if not needed