## Splits the file generated by FindOICInvokes.py
## The invoke chain is defined by the source_integration_code and target_integration_code columns:
## the source calls the target and that target calls another target and so on.
## Find the invoke chains and split the csv file into multiple files. Rows that do not belong to
## any chain (no invoke to/ from others) are placed into a final catch-all chain group, so that
## EVERY SINGLE ROW of the input CSV appears in exactly one chain_group output file.

import pandas as pd
import os
from collections import defaultdict, deque

in_dir = "./output/oic_integrations_backup_20260127_091729/integrations/src"
in_path = in_dir + '/AA-INVOKE-XREFv4.csv'

# Read the CSV; try a couple of engines for robustness
read_attempts = [
    dict(engine='c'),
    dict(engine='python'),
    dict(engine='python', on_bad_lines='skip'),
]
last_err = None
for opts in read_attempts:
    try:
        df = pd.read_csv(in_path, **opts)
        if {'source_integration_code', 'target_integration_code'}.issubset(df.columns):
            break
    except Exception as e:
        last_err = e
        continue
else:
    raise RuntimeError(f"Failed to read CSV with multiple strategies: {last_err}")

# Normalize columns
df.columns = [c.strip() for c in df.columns]

# Keep rows where we actually have an edge (both ends present)
edges_df = df[
    (df['source_integration_code'].notna()) &
    (df['target_integration_code'].notna())
].copy()

# Normalize potential artifacts (line breaks / backslashes from previews)
for col in ['source_integration_code', 'target_integration_code']:
    edges_df[col] = (
        edges_df[col].astype(str)
        .str.replace('\n', '', regex=False)
        .str.replace('\\', '', regex=False)
        .str.strip()
    )

# --------------------------------------------------------------------
# Build UNDIRECTED adjacency (weakly connected components) from edges
# --------------------------------------------------------------------
adj = defaultdict(set)
for _, row in edges_df.iterrows():
    s = row['source_integration_code']
    t = row['target_integration_code']
    if not s or not t or s == 'nan' or t == 'nan':
        continue
    adj[s].add(t)
    adj[t].add(s)

# BFS over nodes to find components
visited = set()
components = []
for node in adj.keys():
    if node in visited:
        continue
    comp = set()
    q = deque([node])
    visited.add(node)
    while q:
        u = q.popleft()
        comp.add(u)
        for v in adj[u]:
            if v not in visited:
                visited.add(v)
                q.append(v)
    components.append(sorted(comp))

# Map node → component id
node_to_comp = {}
for idx, comp in enumerate(components, start=1):
    for n in comp:
        node_to_comp[n] = idx

# ----------------------------------------------------------
# Assign each original row to a component if either source
# or target belongs to that component
# ----------------------------------------------------------
comp_rows = defaultdict(list)
assigned_indices = set()

for i, row in df.iterrows():
    s = str(row.get('source_integration_code', '')).replace('\n', '').replace('\\', '').strip()
    t = str(row.get('target_integration_code', '')).replace('\n', '').replace('\\', '').strip()
    comp_id = None
    if s in node_to_comp:
        comp_id = node_to_comp[s]
    if t in node_to_comp:
        comp_id = node_to_comp[t] if comp_id is None else comp_id

    if comp_id is not None:
        comp_rows[comp_id].append(i)
        assigned_indices.add(i)

# ----------------------------------------------------------
# NEW: Catch-all chain group for "unassigned" rows
#      (rows that do not participate in any chain).
# This guarantees EVERY input row ends up in ONE group.
# ----------------------------------------------------------
all_indices = set(df.index.tolist())
unassigned = sorted(all_indices - assigned_indices)
if unassigned:
    catchall_id = (max(comp_rows.keys()) if comp_rows else 0) + 1
    comp_rows[catchall_id] = unassigned

    # Also reflect this in the components/manifest as a set of "standalone markers".
    # We'll use a synthetic member label so the manifest stays informative.
    # If you prefer to list actual source_integration_code values here, you can gather them too.
    components.append(["__CATCH_ALL__"])

# --------------------------------
# Write results (one CSV per group)
# --------------------------------
outputDir = in_dir + '/invoke_chains'
os.makedirs(outputDir, exist_ok=True)
out_files = []

for comp_id, idxs in comp_rows.items():
    sub = df.loc[idxs].sort_values(
        by=['source_integration_code', 'target_integration_code', 'call_type', 'invoke'],
        kind='stable'
    )
    out_name = os.path.join(outputDir, f'invoke_chain_group_{comp_id:03d}.csv')
    sub.to_csv(out_name, index=False)
    out_files.append(out_name)

# -------------------------------
# Manifest for quick review
# -------------------------------
manifest_rows = []
for comp_id, nodes in enumerate(components, start=1):
    manifest_rows.append({
        'chain_group': comp_id,
        'members_count': len(nodes),
        'members': ';'.join(nodes),
        'rows_in_csv': len(comp_rows.get(comp_id, [])),
    })
manifest = pd.DataFrame(manifest_rows).sort_values(by='rows_in_csv', ascending=False)
manifest.to_csv(os.path.join(outputDir, 'manifest.csv'), index=False)

print("Split files at: ", outputDir)